# Generated by Django 6.0.3 on 2026-04-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
